DISABLE:
  - COPYPASTE
  - SPELL
  - REPOSITORY
  - YAML
  - JSON

ENABLE:
  - MARKDOWN
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK

APPLY_FIXES: false

MARKDOWN_MARKDOWNLINT_CONFIG_RULES:
  MD013:
    enabled: true
    line_length: 120
  MD033:
    enabled: true

MARKDOWN_MARKDOWN_TABLE_PADDING: force
MARKDOWN_REMARK_INDENT: 2

VALIDATE_ALL_CODEBASE: false
FLAVOR_SUGGESTIONS: false